# code=yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-action.json

name: "Query Doctor"
description: "Query Doctor"

inputs:
  begin_date:
    description: "Begin date to start analyzing logs"
    required: false
  log_path:
    description: "Path to the Postgres logs"
    required: true
  postgres_url:
    description: "Postgres URL"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
