FROM denoland/deno:alpine

# Install pgbadger dependencies
RUN apk add --no-cache \
    perl \
    wget \
    make \
    git

# Download, build, and install pgBadger
ARG PGBADGER_VERSION=13.1
WORKDIR /tmp
RUN wget https://github.com/darold/pgbadger/archive/v${PGBADGER_VERSION}.tar.gz && \
    tar -xzf v${PGBADGER_VERSION}.tar.gz && \
    cd pgbadger-${PGBADGER_VERSION} && \
    perl Makefile.PL && \
    make && \
    make install && \
    rm -rf /tmp/pgbadger*

# RUN curl -L https://github.com/supabase-community/postgres-language-server/releases/download/<version>/postgrestools_aarch64-apple-darwin -o postgrestools
# RUN chmod +x postgrestools

WORKDIR /app

# Copy dependency files
COPY deno.json deno.lock* ./

RUN deno install --frozen-lockfile
# Cache dependencies
# RUN deno cache main.ts

# Development command
CMD ["deno", "run", "dev"]
