# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Test with Postgres

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Postgres
        run: |
          sudo tee -a /etc/postgresql/16/main/postgresql.conf <<EOF
            shared_preload_libraries = 'auto_explain'
            auto_explain.log_min_duration = 0
            auto_explain.log_analyze = true
            auto_explain.log_verbose = true
            auto_explain.log_buffers = true
            auto_explain.log_format = 'json'
            logging_collector = on
            log_directory = '/var/log/postgresql'
            log_filename = 'postgres.log'
          EOF
          sudo tee /etc/postgresql/16/main/pg_hba.conf > /dev/null <<EOF
            host all all 127.0.0.1/32 trust
            host all all ::1/128 trust
            local all all peer
          EOF
          sudo systemctl start postgresql.service
          sudo -u postgres createuser -s -d -r -w query_doctor
          sudo -u postgres createdb testing
          sudo chmod 666 /var/log/postgresql/postgres.log

      - name: Apply SQL file
        run: |
          psql -h localhost -U query_doctor -d testing -f bootstrap.sql

      - name: Run local GitHub Action
        uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
          POSTGRES_URL: http://query_doctor@localhost:5432/testing
